PAWS-NDV-PetLovers/Models/Transactions/Billing.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PAWS_NDV_PetLovers.Models.Records;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PAWS_NDV_PetLovers.Models.Transactions
{
    public class Billing
    {
        [Key]
        public int billingId { get; set; }

        [ForeignKey("Diagnostics")]
        public int? DiagnosticsId { get; set; }

        [ForeignKey("Purchases")]
        public int? PurchaseId { get; set; }

        [DataType(DataType.Date)]
        public DateTime date { get;set; }

        [Display(Name ="Grand Total")]
        public double? grandTotal { get; set; }

        [Display(Name = "Cash Receive")]
        public double? cashReceive { get; set; }

        [Display(Name = "Change Amount")]
        public double? changeAmount { get; set; }


        //navigation property

        public Diagnostics? diagnostics { get; set; }

        public Purchase? purchase { get; set; }


        public IList<StockAdjustment>? stockAdjustments { get; set; }

    }
}

PAWS-NDV-PetLovers/Components/BillingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PAWS_NDV_PetLovers.Data;
using PAWS_NDV_PetLovers.ViewModels;

namespace PAWS_NDV_PetLovers.Components
{
    public class BillingViewComponent : ViewComponent
    {
        private readonly PAWS_NDV_PetLoversContext _context;

        public BillingViewComponent(PAWS_NDV_PetLoversContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int? id, bool? PaymentErrorMessage)
        {

            var diagnostics = await _context.Diagnostics
                .Include(d => d.IdiagnosticDetails)
                .ThenInclude(dd => dd.Services)
                .FirstOrDefaultAsync(d => d.diagnostic_Id == id);



            var purchase = await _context.PurchaseDetails
                .Include(p => p.Purchase)
                .Include(p => p.product)
                .Where(p => p.Purchase.diagnosisId_holder == id)
                .ToListAsync();


            var tvm = new TransactionsVm
            {
                Diagnostics = diagnostics,
                IPurchaseDetails = purchase,
                PaymentErrorMessage = PaymentErrorMessage
            };

            return View(tvm);
        }
    }
}

PAWS-NDV-PetLovers/Components/DiagnosticsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PAWS_NDV_PetLovers.Data;
using PAWS_NDV_PetLovers.ViewModels;

namespace PAWS_NDV_PetLovers.Component
{
    public class DiagnosticsViewComponent:ViewComponent
    {
        private readonly PAWS_NDV_PetLoversContext _context;

        public DiagnosticsViewComponent(PAWS_NDV_PetLoversContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync(int? id)
        {

            var diagnostics = await _context.Diagnostics
                            .Include(d => d.PurchaseNav)
                            .ThenInclude(p => p.purchaseDetails)
                            .ThenInclude(p => p.product)
                            .Include(d => d.pet)
                            .ThenInclude(p => p.owner)
                            .Include(d => d.IdiagnosticDetails)
                            .ThenInclude(dd => dd.Services)
                            .FirstOrDefaultAsync(d => string.IsNullOrEmpty(d.status) && id == d.diagnostic_Id);
       

            var vm = new TransactionsVm
            {
                Diagnostics = diagnostics,

            };

            return View(vm);
        }
    }
}

PAWS-NDV-PetLovers/Components/PurchaseViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PAWS_NDV_PetLovers.Data;
using PAWS_NDV_PetLovers.Models.Transactions;
using PAWS_NDV_PetLovers.ViewModels;

namespace PAWS_NDV_PetLovers.Components
{
    public class PurchaseViewComponent:ViewComponent
    {
        private readonly PAWS_NDV_PetLoversContext _context;

        public PurchaseViewComponent(PAWS_NDV_PetLoversContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int? id, bool? errorMessage, bool? RemoveErrorMessage)
        {

            if (errorMessage == true)
            {
                // Add an error message to the ViewData to display on the view
                ViewData["ErrorMessage"] = "No products were selected. Please select at least one product to proceed.";

            }

            if(RemoveErrorMessage == true)
            {
                ViewData["RemoveErrorMessage"] = "Please enter tht total number of decrement";
            }

            var Purchase = await _context.Purchases
                .Include(p => p.purchaseDetails)
                .ThenInclude(p => p.product)
                .ThenInclude(p => p.category)
                .FirstOrDefaultAsync(p => p.diagnosisId_holder == id);

            //VIEW Cart

            var PurchaseItems = await _context.PurchaseDetails
                .Include(p => p.product)
                .ThenInclude(p => p.category)
                .Include(p => p.Purchase)
                .Where(p => p.Purchase.diagnosisId_holder == id && string.IsNullOrEmpty(p.Purchase.status))
                .ToListAsync();


            var vm = new TransactionsVm
            {
                Diagnostics = await _context.Diagnostics
                .Include(p => p.pet)
                .ThenInclude( p=> p.owner)
                .Include(d => d.IdiagnosticDetails)
                .ThenInclude(dd => dd.Services)
                .FirstOrDefaultAsync(d => d.diagnostic_Id == id),
                Purchase = Purchase,
                IProducts = await _context.Products.Include(p => p.category).ToListAsync(),
                IPurchaseDetails = PurchaseItems,
       
            };
       
            return View(vm);
        }
    }
}

PAWS-NDV-PetLovers/Controllers/Transactions/BillingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PAWS_NDV_PetLovers.Data;
using PAWS_NDV_PetLovers.Models.Records;
using PAWS_NDV_PetLovers.Models.Transactions;
using PAWS_NDV_PetLovers.ViewModels;

namespace PAWS_NDV_PetLovers.Controllers.Transactions
{
    [ServiceFilter(typeof(AuthFilter))]
    public class BillingController : Controller
    {
        private PAWS_NDV_PetLoversContext _context;
        public BillingController(PAWS_NDV_PetLoversContext context)
        {
            _context = context;
        }

        public IActionResult Index(TransactionsVm vcm)

        {
            if (vcm.activeBoardTab == null)
            {
                vcm.activeBoardTab = DBoardTab.DBoard_Diagnostics;
            }
            return View(vcm);
        }


        public IActionResult SwitchToDboardTab(string? tabName)
        {
            var vm = new TransactionsVm();

            switch (tabName)
            {
                case "DBoard_Diagnostics":
                    vm.activeBoardTab = DBoardTab.DBoard_Diagnostics;
                    break;


                case "DBoard_Purchase":
                    vm.activeBoardTab = DBoardTab.DBoard_Purchase;
                    break;

                default:
                    vm.activeBoardTab = DBoardTab.DBoard_Diagnostics;
                    break;
            }
            return RedirectToAction(nameof(Index), vm);
        }

        public IActionResult SwitchToTab(string? tabName)
        {
            var vm = new TransactionsVm();

            switch (tabName)
            {
                case "Diagnostics":
                    vm.activeBillingTab = BillingTab.Diagnosis;
                    break;

                case "Purchase":
                    vm.activeBillingTab = BillingTab.Purchase;
                    break;

                case "Billing":
                    vm.activeBillingTab = BillingTab.Billing;
                    break;

                default:
                    vm.activeBillingTab = BillingTab.Diagnosis;
                    break;
            }

            return RedirectToAction(nameof(Index), vm);
        }


        public IActionResult SwitchToHistoryTab(string? tabName)
        {
            var vm = new TransactionsVm();

            switch (tabName)
            {
                case "All":
                    vm.activeHistoryTab = BillingHistoryTab.All;
                    break;

                case "Diagnostics":
                    vm.activeHistoryTab = BillingHistoryTab.Diagnostics;
                    break;

                case "Purchase":
                    vm.activeHistoryTab = BillingHistoryTab.Purchase;
                    break;

            default:
                vm.activeHistoryTab = BillingHistoryTab.All;
                break;
            }

            return RedirectToAction(nameof(BillingHistory), vm);
        }





        [HttpGet]
        public async Task<IActionResult> Edit(int? id, bool? errorMessage, bool? RemoveErrorMessage, bool? PaymentErrorMessage, TransactionsVm tvm)
        {
            // Extract only the date part (ignoring time)

            if (id == null)
            {
                return NotFound();
            }

            //fetched the data in database
            var firstAsync = await _context.Diagnostics
                .Include(d => d.pet)
                .ThenInclude(d => d.owner)
                .Include(d => d.IdiagnosticDetails)
                .ThenInclude(dd => dd.Services)
                .FirstOrDefaultAsync(d => d.diagnostic_Id == id);


            if (tvm.activeBillingTab == null)
            {
                tvm.activeBillingTab = BillingTab.Diagnosis;
            }

            TransactionsVm vm = new TransactionsVm
            {
                Diagnostics = firstAsync,
                activeBillingTab = tvm.activeBillingTab,
                errorMessage = errorMessage,
                RemoveErrorMessage = RemoveErrorMessage,
                PaymentErrorMessage = PaymentErrorMessage
            };

            return View(vm);

        }


        //billing switch Tabs
        public IActionResult SwitchToBillingTab(int? id, string? tabName)
        {

            //object instantiation
            var vm = new TransactionsVm();

            switch (tabName)
            {
                case "Diagnosis":
                    vm.activeBillingTab = BillingTab.Diagnosis;
                    break;

                case "Purchase":
                    vm.activeBillingTab = BillingTab.Purchase;
                    break;

                case "Billing":
                    vm.activeBillingTab = BillingTab.Billing;
                    break;
            }

            return RedirectToAction(nameof(Edit), new { id = id, vm.activeBillingTab });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Diagnostics")] TransactionsVm tvm)
        {
            double totalPurchase = 0;

            // Extract the Diagnostics object from the view model
            var diagnostics = tvm.Diagnostics;


            // Referenced from view for Update detail Results
            foreach (var detail in diagnostics.IdiagnosticDetails)
            {
                // FindAsync the DetailID
                var existingDetail = await _context.DiagnosticDetails.FindAsync(detail.diagnosticDet_Id);

                // Update the diagnosis details
                if (existingDetail != null)
                {
                    existingDetail.details = detail.details;
                }
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DiagnosticExists(diagnostics.diagnostic_Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }


            //for Diagnostic Bill Display

            var diagnostic = await _context.Diagnostics
               .Include(d => d.PurchaseNav)
                   .ThenInclude(p => p.purchaseDetails)
                   .ThenInclude(p => p.product)
               .Include(d => d.pet)
                   .ThenInclude(p => p.owner)
               .Include(d => d.IdiagnosticDetails)
                   .ThenInclude(dd => dd.Services)
               .Where(d => string.IsNullOrEmpty(d.status))
               .ToListAsync();

            var purchase = await _context.Purchases
                .Include(p => p.purchaseDetails).ToListAsync();

            TransactionsVm vm = new TransactionsVm
            {
                IDiagnostics = diagnostic,
                IPurchase = purchase
            };

            return RedirectToAction("Index", "BillingDashboard"); // Redirect to a different action after saving
        }

        #region == Functions == 
        private bool DiagnosticExists(int id)
        {
            return _context.Diagnostics.Any(e => e.diagnostic_Id == id);
        }

        private bool PurchaseExists(int? id)
        {
            return _context.Purchases.Any(p => p.purchaseId == id);
        }
        #endregion

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePurchaseDiagnostics(int? diagnosticid, Purchase purchase)
        {
            if (purchase == null || purchase.purchaseDetails == null || !purchase.purchaseDetails.Any())
            {
                // Fetch the original data for the view
                var diagnostics = await _context.Diagnostics
                    .Include(d => d.pet)
                    .ThenInclude(p => p.owner)
                    .Include(d => d.IdiagnosticDetails)
                    .ThenInclude(dd => dd.Services)
                    .Include(d => d.PurchaseNav)
                    .ThenInclude(d => d.purchaseDetails)
                    .ThenInclude(pd => pd.product)
                    .ThenInclude(p => p.category)
                    .FirstOrDefaultAsync(d => d.diagnostic_Id == diagnosticid);

                var purchaseItems = await _context.PurchaseDetails
                    .Include(p => p.product)
                    .ThenInclude(p => p.category)
                    .Include(p => p.Purchase)
                    .Where(p => p.Purchase.diagnosisId_holder == diagnosticid && string.IsNullOrEmpty(p.Purchase.status))
                    .ToListAsync();

                // Calculate the total price again
                /*double purchasePayment = purchaseItems.Sum(item => (double)item.product.sellingPrice * (int)item.quantity);*/

                // Reload the view model with the original data and an error message
                var viewModel = new TransactionsVm
                {
                    Diagnostics = diagnostics,
                    Purchase = await _context.Purchases
                        .Include(p => p.purchaseDetails)
                        .ThenInclude(p => p.product)
                        .ThenInclude(p => p.category)
                        .FirstOrDefaultAsync(p => p.diagnosisId_holder == diagnosticid),
                    Services = await _context.Services.ToListAsync(),
                    IProducts = await _context.Products.Include(p => p.category).ToListAsync(),
                    IPurchaseDetails = purchaseItems,
                    /* totalPurchasePayment = purchasePayment,*/
                    activeBillingTab = BillingTab.Purchase
                };

                TempData["Title"] = "Successfully Creted";
                return RedirectToAction("Edit", new { id = diagnosticid, errorMessage = true, viewModel.activeBillingTab });
            }

            //if purchase not null in the View
            var existingPurchase = await _context.Purchases
                .Include(p => p.purchaseDetails)
                .ThenInclude(pd => pd.product)

PAWS-NDV-PetLovers/Views/Billing/BillingHistory.cshtml
@model PAWS_NDV_PetLovers.ViewModels.TransactionsVm
@{
    ViewData["Title"] = "Billing History -> ALL TRANSACTION HISTORY";
}

<div class="container p-0 bg container-bord shadow mb-5 bg-white rounded">

    <div class="container p-0">

        <div class="container p-0  bg-custom-color text-center">

            <div>
                <div class="container p-2">
                    <h1 class ="fw-bold">Transaction History</h1>
                </div>
            </div>

        </div>


        <div class="btn-group btn-group-toggle pt-5 mx-3" data-toggle="buttons">
            <a role="presentation" asp-action="SwitchToHistoryTab" asp-route-tabName="All" class="@(Model.activeHistoryTab == PAWS_NDV_PetLovers.ViewModels.BillingHistoryTab.All ? "active" : string.Empty) btn btn-success btn-lg">All</a>
            <a role="presentation" asp-action="SwitchToHistoryTab" asp-route-tabName="Diagnostics" class="@(Model.activeHistoryTab == PAWS_NDV_PetLovers.ViewModels.BillingHistoryTab.Diagnostics ? "active" : string.Empty) btn btn-success btn-lg">Diagnosis</a>
            <a role="presentation" asp-action="SwitchToHistoryTab" asp-route-tabName="Purchase" class="@(Model.activeHistoryTab == PAWS_NDV_PetLovers.ViewModels.BillingHistoryTab.Purchase ? "active" : string.Empty) btn btn-success btn-lg">Purchases</a>
        </div>


        @switch (Model.activeHistoryTab)
        {
            case PAWS_NDV_PetLovers.ViewModels.BillingHistoryTab.All:
                @await Component.InvokeAsync("AllBillingHistory")
                break;

            case PAWS_NDV_PetLovers.ViewModels.BillingHistoryTab.Diagnostics:
                @await Component.InvokeAsync("DiagnosticBillingHistory")
                break;

            case PAWS_NDV_PetLovers.ViewModels.BillingHistoryTab.Purchase:
                @await Component.InvokeAsync("PurchaseBillingHistory")
                break;
        
            default:
                @await Component.InvokeAsync("AllBillingHistory")
                break;
        }
    </div>
</div>

PAWS-NDV-PetLovers/Views/Billing/BillingHistoryView.cshtml
@model PAWS_NDV_PetLovers.ViewModels.TransactionsVm
@{
    ViewData["Title"] = "Billing History View";
}

<div class="container container p-0 bg container-bord shadow  mb-5 bg-white rounded">

    <div class="container p-0">


            <div class="container p-0  bg-custom-color text-center ">
                   <div>
                    <div class="container p-2">
                        <h1 class="fw-bold">Billing Information</h1>
                    </div>
                </div>
            </div>


        <div class="mt-3 me-3 p-3">
            @if (Model.Billing.purchase == null)
            {
                var custmerName = $"{Model.Billing.diagnostics.pet.owner.fname} {Model.Billing.diagnostics.pet.owner.lname}";
                <span><strong> Customer Name: </strong>@custmerName  &nbsp;  &nbsp; &nbsp;</span>
                <strong>Date:</strong> <span>@Model.Billing.date.ToString("MMM. dd, yyyy")</span>
            }
            else
            {
                <span><strong> Customer Name: </strong>@Model.Billing.purchase.customerName  &nbsp;  &nbsp; &nbsp;</span>
                <strong>Date:</strong> <span>@Model.Billing.date.ToString("MMM. dd, yyyy")</span>
            }

            <div class="text-end">
                <a asp-action="BillingHistory" class="btn btn-cancel btn-lg px-4 text-end">Back to History</a>
            </div>
            
        </div>
    
    <div class="card p-3">
        <div class="table-responsive">
            <table class="table table-striped table-bordered hover">
                @* diagnostic *@
                <thead>
                    <tr>
                        <th></th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Billing.diagnostics != null)
                    {
                        <tr>
                            <th colspan="3">Service</th>
                        </tr>
                        @foreach (var service in Model.Billing.diagnostics.IdiagnosticDetails)
                        {
                            <tr>
                                <td class="text-center">@Html.DisplayFor(s => service.Services.serviceName)</td>
                                <td class="text-center">@Html.DisplayFor(s => service.Services.serviceCharge)</td>
                                <td></td> <!-- Empty cell since quantity is not provided -->
                            </tr>
                        }
                    }

                    @* Purchase *@
                    @if (Model.Billing.purchase != null && Model.Billing.purchase.purchaseDetails.Count() != 0)
                    {
                        <tr>
                            <th colspan="3">Purchase</th>
                        </tr>
                        @foreach (var purchase in Model.Billing.purchase.purchaseDetails)
                        {
                            <tr>
                                <td class="text-center">@Html.DisplayFor(s => purchase.product.productName)</td>
                                <td class="text-center">@Html.DisplayFor(s => purchase.product.sellingPrice)</td>
                                <td class="text-center">@Html.DisplayFor(s => purchase.quantity)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="mt-2 p-3 text-end">
        @{
            var total = @Model.Billing.grandTotal;
            var grandTotal = (double)total;

            var cash = @Model.Billing.cashReceive;
            var tendered = (double)cash;

            var change = @Model.Billing.changeAmount;
            var totalChange = (double)change;
        }
        <strong>Grand Total : <span class="text-danger fw-bold">@grandTotal.ToString("C")</span></strong> <br />
        <strong>Cash Tendered : <span class=" fw-bold">@tendered.ToString("C")</span></strong><br />
        <strong>Change : <span class=" fw-bold">@totalChange.ToString("C")</span></strong>
    </div>

   
    </div>
</div>

PAWS-NDV-PetLovers/Views/Billing/Edit.cshtml
        @model PAWS_NDV_PetLovers.ViewModels.TransactionsVm

@{
    ViewData["Title"] = "Billing Diagnostic - Edit";
}


<div class="container p-0 bg container-bord shadow mb-5 bg-white rounded">



    <div class="container p-0 ">
        <div class="container p-0  bg-custom-color text-center">
            <div>
                <div class="container p-2">
                    <h1 class="fw-bold">Pet Information</h1>
                </div>
            </div>
        </div>
    </div>


    <form method="post" asp-action="Edit"> <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="row p-3 pt-3">

                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label class="control-label">Owner ID - Name</label>
                        <input value="@($"{Model.Diagnostics.pet.owner.id} - {Model.Diagnostics.pet.owner.fname} {Model.Diagnostics.pet.owner.lname}")" class="form-control" readonly />
                    </div>

                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label asp-for="Diagnostics.diagnostic_Id" class="control-label"></label>
                        <input class="form-control" asp-for="Diagnostics.diagnostic_Id" readonly />
                    </div>

                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label asp-for="Diagnostics.petId" class="control-label"></label>
                        <input asp-for="Diagnostics.petId" class="form-control " readonly />
                    </div>

          
                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label asp-for="Diagnostics.pet.petName" class="control-label"></label>
                        <input asp-for="Diagnostics.pet.petName" class="form-control" readonly />
                    </div>
                    
                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label asp-for="Diagnostics.pet.breed" class="control-label"></label>
                        <input asp-for="Diagnostics.pet.breed" class="form-control" readonly />
                    </div>

                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label asp-for="Diagnostics.pet.gender" class="control-label"></label>
                        <input asp-for="Diagnostics.pet.gender" class="form-control" readonly />
                    </div>

                    <div class="form-group col-lg-3 col-md-6 mb-3" id="apppad">
                        <label asp-for="Diagnostics.weight" class="control-label"></label>
                        <input asp-for="Diagnostics.weight" class="form-control bg-light decimal-input " placeholder="Input weight" value="@Model.Diagnostics.weight" required />
                    </div>


            </div>


            <div class="row p-3 mt-1">
                <div class="form-group col-lg-3 visually-hidden" id="apppad">
                    <!-- Hidden Field for Date -->
                    <label asp-for="Diagnostics.date" class="control-label"></label>
                    <input type="hidden" asp-for="Diagnostics.date" class="form-control dateInput" value="@Model.Diagnostics.date" readonly />
                    <input value="@Model.Diagnostics.date?.ToString("MMM. dd, yyyy")" class="form-control" readonly />

                </div>
        
            </div>

    </form>

       
                    <div class="btn-group btn-group-toggle pt-1 pb-4 mx-3" data-toggle="buttons">
                    
                                <a role="presentation" asp-action="SwitchToBillingTab" asp-route-tabName="Diagnosis" asp-route-id="@Model.Diagnostics.diagnostic_Id" class="@(Model.activeBillingTab == PAWS_NDV_PetLovers.ViewModels.BillingTab.Diagnosis ? "active" : string.Empty) btn btn-success btn-lg">Service</a>
                   
                                <a role="presentation" asp-action="SwitchToBillingTab" asp-route-tabName="Purchase" asp-route-id="@Model.Diagnostics.diagnostic_Id" class="@(Model.activeBillingTab == PAWS_NDV_PetLovers.ViewModels.BillingTab.Purchase ? "active" : string.Empty) btn btn-success btn-lg">Purchase</a>
                    
                                <a role="presentation" asp-action="SwitchToBillingTab" asp-route-tabName="Billing" asp-route-id="@Model.Diagnostics.diagnostic_Id" class="@(Model.activeBillingTab == PAWS_NDV_PetLovers.ViewModels.BillingTab.Billing ? "active" : string.Empty) btn btn-success btn-lg">Billing</a>
                   
                    </div>
        

                    @switch (Model.activeBillingTab)
                    {
                        case PAWS_NDV_PetLovers.ViewModels.BillingTab.Diagnosis:
                            @await Component.InvokeAsync("Diagnostics", new {id = Model.Diagnostics.diagnostic_Id})  //Service on View
                        break;

                                        case PAWS_NDV_PetLovers.ViewModels.BillingTab.Purchase:
                                            @await Component.InvokeAsync("Purchase", new { id = Model.Diagnostics.diagnostic_Id, errorMessage = Model.errorMessage, RemoveErrorMessage = Model.RemoveErrorMessage})
                                         break;

                                        case PAWS_NDV_PetLovers.ViewModels.BillingTab.Billing:
                                            @await Component.InvokeAsync("Billing", new { id = Model.Diagnostics.diagnostic_Id, PaymentErrorMessage = Model.PaymentErrorMessage})
                                        break;

                                        default:
                                        @await Component.InvokeAsync("Diagnosis", new { id = Model.Diagnostics.diagnostic_Id })
                                        break;
                    }

   
</div>

<script src="~/js/TransactionsDT/modalProductTable.js"async></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

PAWS-NDV-PetLovers/Views/Billing/EditDetails.cshtml
@model PAWS_NDV_PetLovers.ViewModels.TransactionsVm

@{
    ViewData["Title"] = "EditDetails";
}

<div class="container p-0 bg container-bord shadow mb-5 bg-white rounded">

    <div class="container p-0">
        <div class="container p-0  bg-custom-color text-center">
            <div>
                <div class="container p-2">
                    <h1 class="fw-bold">Edit Diagnosis</h1>
                </div>
            </div>
        </div>

        <div class="card p-3">
            <div class="table-responsive">
                <form method="post" asp-action="EditDetails">
                     <table class="table table-striped">
                         <thead>
                             <tr class="no-col text-center">
                                 <th>
                                    Service Name 
                                 </th>
                                <th>
                                    Diagnosis
                                </th>
                             </tr>
                         </thead>
                         <tbody>
                             @* get the service details individually to pass on the controller *@
                            @for (int i = 0; i < Model.Diagnostics.IdiagnosticDetails.Count; i++)
                            {
                                <tr>
                                    <td class="text-center">
                                        @Html.DisplayFor(model => Model.Diagnostics.IdiagnosticDetails[i].Services.serviceName)
                                    </td>
                                    <td>
                                        <textarea class="form-control bg-light" rows="5" style="resize: none;" name="Diagnostics.IdiagnosticDetails[@i].details">@Model.Diagnostics.IdiagnosticDetails[i].details</textarea>
                                    </td>

                                    @* id holder for diagnosticDetails *@
                                    <input type="hidden" name="Diagnostics.IdiagnosticDetails[@i].diagnosticDet_Id" value="@Model.Diagnostics.IdiagnosticDetails[i].diagnosticDet_Id" />

                                </tr>
                            }
          
                         </tbody>
                     </table>

                     <div class="form-group mt-4 text-end mb-4 me-4">
                        <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model.Diagnostics.diagnostic_Id" asp-route-tabName="Diagnostics">Cancel</a>
                        <input type="hidden" name="id" value="@Model.Diagnostics.diagnostic_Id" />
                        <input type="submit" class="btn btn-primary px-3" value="Save"/>
                     </div>
                </form>
            </div>
        </div>
    </div>
</div>